### ISSUE TITLE
Addition for the anti-lgbt+ hate list.

### ISSUE THREAD

**Issue by Heather-Herbert** [chigh/hategroup-dnsbl#2]
Please add https://gendercriticalcomingoutday.org/ to the anti-lgbt+ hate list.

**Comment by chigh** [comment]
I'm sorry for the delay. Sure thing, I'll be able to do that later this weekend when I can VPN and use a clean browser setup. I'll put it in the "custom" section. While you and I know that site absolutely belongs, I haven't seen them included in the SPLC list. But I haven't seen when they last updated their data, either.

**Comment by chigh** [comment]
Added!
https://github.com/chigh/hategroup-dnsbl/commit/5255e4c99d94530fa896f306cb44f240db4bfdde
